name: Build API v3
on:
  push:
    branches:
      - main
    tags:
      - api-v3-v[0-9]+.[0-9]+.[0-9]+  # Semver Release
      - api-v3-v[0-9]+.[0-9]+.[0-9]+-**  # Semver Pre-Release
    paths:
      - services/api-v3/**
      - .github/workflows/build-api-v3.yaml
  pull_request:
    branches:
      - main
    paths:
      - services/api-v3/**
      - .github/workflows/build-api-v3.yaml
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Get the version from the tag, if it exists
        run: |
          TAG=${{ github.ref_name }}
          VERSION=$(echo "${TAG}" | sed -E 's/api-v3-v//')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: hub.opensciencegrid.org/macrostrat/api-v3
          tags: |
            type=ref,event=pr,suffix=-{{date 'YYYYMMDDHHmmss'}}
            type=ref,event=branch,suffix=-{{date 'YYYYMMDDHHmmss'}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=main-{{date 'YYYYMMDDHHmmss'}},enable={{is_default_branch}}
            type=raw,value=sha-{{sha}}
            type=raw,value=${{ env.VERSION }},enable=${{ env.VERSION != '' }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to OSG DockerHub
        uses: docker/login-action@v2
        with:
          registry: hub.opensciencegrid.org
          username: ${{ vars.HARBOR_CLI_NAME }}
          password: ${{ secrets.HARBOR_CLI_SECRET }}
      - name: Build and push
        uses: docker/build-push-action@v5
        id: build-and-push
        with:
          context: services/api-v3
          build-contexts: |
            py-modules=./py-modules
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      # Add a link to the built artifact to the workflow summary
      - name: Add link to workflow summary
        run: |
          echo "## Image Built" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The image has been built and pushed to [OSG Harbor](https://hub.opensciencegrid.org/harbor/projects/887/repositories/api-v3/artifacts-tab/artifacts/${{ steps.build-and-push.outputs.digest }})" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Tags:" >> $GITHUB_STEP_SUMMARY
          var="${{ steps.meta.outputs.tags }}"
          for tag in $var; do
            echo "- \`$tag\`" >> $GITHUB_STEP_SUMMARY
          done
